import { DbServiceSettings } from 'moleculer-db';

export interface SettingsServiceSettingsOptions extends DbServiceSettings {}

export enum SettingTypes {

    CHECK_KYC_WITHDRAW = 'CHECK_KYC_WITHDRAW',
    TOP_BINARY_SPONSOR = 'TOP_BINARY_SPONSOR',
    BONUS_ACTIVE_24H_VALUE = 'BONUS_ACTIVE_24H_VALUE',
    BONUS_ACTIVE_24H_CURRENCY = 'BONUS_ACTIVE_24H_CURRENCY',
    SETTING_NETWORK_REF = 'SETTING_NETWORK_REF',
    SETTING_NETWORK_BIN = 'SETTING_NETWORK_BIN',
    SETTING_MAINTANANCE = 'SETTING_MAINTANANCE',
    ID_SPONSOR_TOP = 'ID_SPONSOR_TOP',
    TOKEN_MINT_NFT_RPC = 'TOKEN_MINT_NFT_RPC',
    TOKEN_MINT_NFT = 'TOKEN_MINT_NFT',
    TOKEN_ABI_MINT_NFT = 'TOKEN_ABI_MINT_NFT',
    CONTRACT_MINT_NFT = 'CONTRACT_MINT_NFT',
    CONTRACT_MINT_NFT_RPC = 'CONTRACT_MINT_NFT_RPC',
    CONTRACT_MINT_NFT_TARGET_ADDRESS = 'CONTRACT_MINT_NFT_TARGET_ADDRESS',
    CONTRACT_MINT_NFT_TARGET_PRIVATE_KEY = 'CONTRACT_MINT_NFT_TARGET_PRIVATE_KEY',
    CONTRACT_ABI_MINT_NFT = 'CONTRACT_ABI_MINT_NFT',
	LINK_SCAN_MINT_NFT = 'LINK_SCAN_MINT_NFT',
    RPC_BLOCKCHAIN_SIGN_MESSAGE = 'RPC_BLOCKCHAIN_SIGN_MESSAGE',
    MARKETCAP_PRO_KEY = 'MARKETCAP_PRO_KEY',
}
